# Generated by Django 3.0.6 on 2020-06-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('objs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.oList')),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.sList')),
                ('verbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.vList')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('mean', models.CharField(blank=True, max_length=20)),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Type')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='vlist',
            name='verb',
            field=models.ManyToManyField(to='words.Word'),
        ),
        migrations.AddField(
            model_name='slist',
            name='subject',
            field=models.ManyToManyField(to='words.Word'),
        ),
        migrations.AddField(
            model_name='olist',
            name='obj',
            field=models.ManyToManyField(to='words.Word'),
        ),
    ]
