# Generated by Django 3.0.6 on 2020-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
