# Generated by Django 3.0.6 on 2020-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_wordbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='olist',
            name='theme',
            field=models.CharField(default='tmp', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slist',
            name='theme',
            field=models.CharField(default='tmp', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlist',
            name='theme',
            field=models.CharField(default='tmp', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
