# Generated by Django 3.0.6 on 2020-06-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20200622_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='theme',
        ),
    ]
