# Generated by Django 3.0.6 on 2020-06-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_remove_word_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.Theme'),
        ),
    ]
