# Generated by Django 3.0.6 on 2020-06-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20200622_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
    ]
