# Generated by Django 3.0.6 on 2020-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20200622_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='_class',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordbook',
            name='teacher',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
