# Generated by Django 3.0.6 on 2020-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20200624_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
