# Generated by Django 3.0.6 on 2020-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_auto_20200708_1631'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word_type', 'word'), name='unq'),
        ),
    ]
