# Generated by Django 3.0.6 on 2020-07-14 07:53

from django.db import migrations, models
import words.models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_auto_20200713_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to=words.models.cp),
        ),
    ]
