# Generated by Django 3.0.6 on 2020-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_auto_20200714_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olist',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='slist',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='vlist',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='description',
        ),
    ]
