# Generated by Django 3.0.6 on 2020-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_auto_20200729_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='zoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cLass', models.CharField(max_length=10)),
                ('tEacher', models.CharField(max_length=50)),
                ('lInk', models.CharField(max_length=100)),
            ],
        ),
    ]
