# Generated by Django 3.0.6 on 2020-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom',
            name='see',
            field=models.BooleanField(default=True),
        ),
    ]
